name: 'Zeugwerk CI/CD Action'
description: 'Build and Test a TwinCAT3 project with a Zeugwerk CI/CD server.'
branding:
  icon: 'book-open'
  color: 'gray-dark'
inputs:
  username:
    description: 'Username for the Zeugwerk CI/CD Service'
    required: true
    default: ''
  password:
    description: 'Password for the Zeugwerk CI/CD Service'
    required: true
    default: ''
  tcversion:
    description: 'TwinCAT Version (i.e. TC3.1.4024.22) that should be used to compile and test the PLCs. The TwinCAT Version has to be available on a Zeugwerk CI/CD Server. If empty, an arbitrary TwinCAT version, which is available on the Zeugwerk CI environment, is used.'
    required: false
    default: ''    
  platform:
    description: 'What platform to build for'
    required: false
    default: 'TwinCAT RT (x64)'    
  variant-build:
    description: 'Allows to specify which variant of the PLC should be built'
    required: false
    default: ''    
  variant-test:
    description: 'Allows to specify which variant of the PLC should be tested (e.g. usually this is a variant without hardware)'
    required: false
    default: ''    
  static-analysis:
    description: 'Run TwinCAT static analysis - light or advanced, depending what your username has access to. Open source users only have access to the light variant. Static analysis settings specified in the PLC proj files are used.'
    required: false
    default: 'false'    
  installer:
    description: 'Build a Installer so that the PLC can be installed on a Target via a Windows PC.'
    required: false
    default: 'false'    
  workspace:
    description: 'Folder, which contains the .Zeugwerk folder, defaults to ./'
    required: false
    default: './'    
  version:
    description: 'If set to a valid version number (e.g. 1.2.3.4, 1.2.3-alpha), zkbuild will create the artifacts with the passed version number instead of using the latest (version) tag of the repository'
    required: false
    default: ''
  skip-build:
    description: 'If set to true, zkbuild will skip building the artifact of the project. This can be useful to speed up the build process if you are only interested in the outcome of the unittests'
    required: false
    default: 'false'
  skip-test:
    description: 'If set to true, zkbuild will skip building and executing the unit tests defined in the project'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.tcversion }}    
    - ${{ inputs.workspace }}    
    - ${{ inputs.version }}    
    - ${{ inputs.skip-build }}    
    - ${{ inputs.skip-test }}    
    - ${{ inputs.variant-build }}    
    - ${{ inputs.variant-test }}    
    - ${{ inputs.static-analysis }}
    - ${{ inputs.installer }}
    - ${{ inputs.platform }}
    - ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
