name: 'Zeugwerk CI/CD Action'
description: 'Build and Test a TwinCAT3 project with a Zeugwerk CI/CD server.'
branding:
  icon: 'book-open'
  color: 'gray-dark'
inputs:
  username:
    description: 'Username for the Zeugwerk CI/CD Service'
    required: true
    default: ''
  password:
    description: 'Password for the Zeugwerk CI/CD Service'
    required: true
    default: ''
  tcversion:
    description: 'TwinCAT Version (i.e. TC3.1.4024.22) that should be used to compile and test the PLCs. The TwinCAT Version has to be available on a Zeugwerk CI/CD Server. If empty, a arbitrary TwinCAT version, which is available on the Zeugwerk CI environment, is used.'
    required: false
    default: ''    
  workspace:
    description: 'Folder, which contains the .Zeugwerk folder, defaults to ./'
    required: false
    default: './'    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.tcversion }}    
    - ${{ inputs.workspace }}    
