name: 'Zeugwerk CI/CD Action'
description: 'Build and Test a TwinCAT3 project with a Zeugwerk CI/CD server.'
branding:
  icon: 'book-open'
  color: 'gray-dark'
inputs:
  username:
    description: 'Username for the Zeugwerk CI/CD Service'
    required: true
    default: ''
  password:
    description: 'Password for the Zeugwerk CI/CD Service'
    required: true
    default: ''
  filepath:
    description: 'Path to a Zeugwerk config.json file'
    required: true
    default: ''
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.filepath }}
    - ${{ inputs.working-directory }}
